### ISSUE TITLE
MCP3208 Potential Adjustments

### ISSUE THREAD

**Issue by CL16gtgh** [hytech-racing/MCU#28]
- Generalize library to accommodate IC's of the same series but with different parameters
   - e.g. MCP3204
- Add implementation for AnalogMultiSensor get() function

**Comment by CL16gtgh** [comment]
I already did those to compile main but feel free to adjust it if necessary

**Comment by Dopp-IO** [comment]
Templated MCP3208 into MCP_ADC.
