### ISSUE TITLE
Rework TC Mux

### ISSUE THREAD

**Issue by RCMast3r** [hytech-racing/MCU#61]
- [ ] only have one controller operating at once
- [ ] only have one controller output be gotten out of the tc mux and make it a functional thing instead of a member variable 
- [ ] make a clear safety manager for the values gotten from the torque controllers
- [ ] remove sub-ticking of random logic checking and ensure that there doesnt exist nested tick stuff as this can introduce conflicts for stuff
- [ ] create state estimation system that receives input from all sensors and then creates a shared system state that is given to the controllers.

**Comment by RCMast3r** [comment]
we can just make the torque controllers each different "systems" with each inheriting from a base class that just has the output function and an input that contains a super-state of the car that has every variable that is needed by all the controllers that gets fed by the sensors of the car. this state estimator should handle all of the filtering and sensor data unification for ease of distributing to the controllers. It can just be given access to the CAN interface and the other sensor interfaces.

**Comment by walkermburns** [comment]
This is probably out of scope for FS Invitational, but we can try.
TC MUX and State Estimator should be seperate issues and are each a pretty big project. TC MUX rework is probably higher priority

**Comment by walkermburns** [comment]
Taking this out of the Formula South Milestone, we are just going to have to work with what we got for now.
