### ISSUE TITLE
Make sure pedal 'sense' max/min margins are reasonable

### ISSUE THREAD

**Issue by RCMast3r** [hytech-racing/MCU#62]
right now the margins can scale the possible value below or above the range of the sensor. we need to also cap the scaled min / max of the sensor to being within 0 to max of sensor.

**Comment by walkermburns** [comment]
These should be an arbitrary amount higher and lower than max and min in case the pedal is completely disconnected, we need to trip implausibility if the values are floating around their max/min values

**Comment by shaynoorani** [comment]
Done
